# Generated by Django 5.1.2 on 2024-10-23 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0002_alter_message_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="channel",
            options={"verbose_name": "Канал", "verbose_name_plural": "Каналы"},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "Сообщение", "verbose_name_plural": "Сообщения"},
        ),
        migrations.AlterField(
            model_name="channel",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название канала"),
        ),
        migrations.AlterField(
            model_name="channel",
            name="participants",
            field=models.ManyToManyField(
                related_name="channels",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Участники",
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="password",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Пароль"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="chats.channel",
                verbose_name="Канал",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Отправитель",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.TextField(verbose_name="Текст сообщения"),
        ),
    ]
